version: "1"

services:
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: node
    volumes:
      - ./src:/home/node/app/src
    container_name: type-library
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: npm start
  mongodb_container:
    # This image automatically creates a replica set required for transactions
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      INIT_WAIT_SEC: 3
    ports:
      - 27017:27017
